# Generated by Django 5.1.7 on 2025-03-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={'verbose_name': 'Tenant', 'verbose_name_plural': 'Tenants'},
        ),
        migrations.AddField(
            model_name='tenant',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='id_number_or_passport',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='phone_number',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='physical_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='workplace',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='occupation',
            field=models.CharField(blank=True, choices=[('employed', 'Employed'), ('self_employed', 'Self Employed'), ('student', 'Student'), ('retired', 'Retired'), ('unemployed', 'Unemployed'), ('other', 'Other')], max_length=150, null=True),
        ),
    ]
