# Generated by Django 5.1.7 on 2025-03-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_tenant_options_tenant_emergency_contact_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landlord',
            options={'verbose_name': 'Landlord', 'verbose_name_plural': 'Landlords'},
        ),
        migrations.RemoveField(
            model_name='landlord',
            name='user',
        ),
        migrations.AddField(
            model_name='landlord',
            name='aob',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='landlord',
            name='email',
            field=models.EmailField(default='unknown@example.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='landlord',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=150),
        ),
        migrations.AddField(
            model_name='landlord',
            name='id_number',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name='landlord',
            name='middle_name',
            field=models.CharField(default='Unknown', max_length=150),
        ),
        migrations.AddField(
            model_name='landlord',
            name='other_names',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='landlord',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='landlord',
            name='physical_address',
            field=models.CharField(default='Unknown', max_length=200),
        ),
    ]
