# Generated by Django 5.1.7 on 2025-03-30 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_apartment_options_alter_apartmenttype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
