# Generated by Django 5.1.7 on 2025-04-02 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_invoice_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 5, 2, 7, 36, 20, 544200, tzinfo=datetime.timezone.utc)),
        ),
    ]
