# Generated by Django 5.1.7 on 2025-04-02 12:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_invoice_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 5, 2, 12, 15, 58, 444586, tzinfo=datetime.timezone.utc)),
        ),
    ]
